cake2/App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    # url(r'^(\d+)/$',views.index,name='index'),
    url(r'^all/$',views.all,name='all'),
    # url(r'^all/(\d+)/$',views.all,name='all'),
    url(r'^cake/$',views.cake,name='cake'),
    url(r'^classics/$',views.classics,name='classics'),
    url(r'^children/$', views.children, name='children'),
    url(r'^zunai/$', views.zunai, name='zunai'),
    url(r'^snacks/$', views.snacks, name='snacks'),
    url(r'^we/$', views.we, name='we'),

    # url(r'^base/$',views.base,name='base'),
    # url(r'^detailed/$',views.detailed,name='detailed'),
    url(r'^detailed/(\d+)/$',views.detailed,name='detailed'),
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^jiesuan/$',views.jiesuan,name='jiesuan'),
    # url(r'^order_detail/$',views.order_detail,name='order_detail'),


    url(r'^register/$',views.register,name='register'),
    url(r'^login/$',views.user_login,name='login'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^yzm/$',views.get_yzm,name='yzm'),



    url(r'^add/$',views.add,name='add'),

    url(r'^user/$',views.user,name='user'),
    url(r'^order/$', views.order, name='order'),
    url(r'^favorite/$', views.favorite, name='favorite'),
    url(r'^friend/$', views.friend, name='friend'),
    url(r'^address/$', views.address, name='address'),
    url(r'^integral/$', views.integral, name='integral'),
    url(r'^bonus/$', views.bonus, name='bonus'),
    url(r'^message/$', views.message, name='message'),

    url(r'^changem/$', views.changem, name='changem'),
    url(r'^phone_num/$', views.phone_num, name='phone_num'),

    url(r'^editpwd/$', views.editpwd, name='editpwd'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^paysucceed/$', views.paysucceed, name='paysucceed'),

]

cake2/cake/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('App.urls', namespace='app'))
]

cake2/App/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.contrib.auth.models import AbstractUser
from django.db import models


class Category(models.Model):
    cid = models.AutoField(primary_key=True)
    cname = models.CharField(max_length=60)
    parentid = models.IntegerField()
    compere = models.CharField(max_length=30, blank=True, null=True)
    description = models.CharField(max_length=1000, blank=True, null=True)
    orderby = models.IntegerField(blank=True, null=True)
    namestyle = models.CharField(max_length=10, blank=True, null=True)
    logo = models.CharField(max_length=200, blank=True, null=True)
    themenum = models.IntegerField(blank=True, null=True)
    replynum = models.IntegerField(blank=True, null=True)
    lastpost = models.CharField(max_length=600, blank=True, null=True)

    class Meta:
        # managed = False
        db_table = 'category'


class Friendlink(models.Model):
    site = models.CharField(max_length=100)
    url = models.CharField(max_length=200, blank=True, null=True)
    logo = models.CharField(max_length=300, blank=True, null=True)
    orderby = models.IntegerField(blank=True, null=True)
    description = models.CharField(max_length=300, blank=True, null=True)

    class Meta:
        # managed = False
        db_table = 'friendlink'


class Lockip(models.Model):
    ip = models.CharField(max_length=20)
    starttime = models.DateTimeField(blank=True, null=True)
    endtime = models.DateTimeField(blank=True, null=True)

    class Meta:
        # managed = False
        db_table = 'lockip'


class Order(models.Model):
    oid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100,blank=True, null=True)
    ordernumber = models.IntegerField()
    money = models.IntegerField()
    create_time = models.DateTimeField(blank=True, null=True)
    paytime = models.DateTimeField(blank=True, null=True)
    paytype = models.SmallIntegerField(blank=True, null=True)
    unit_price = models.IntegerField(blank=True, null=True)
    total_price = models.IntegerField(blank=True, null=True)
    num = models.IntegerField(blank=True, null=True)
    isdel = models.SmallIntegerField(blank=True, null=True,default=0)
    iscart = models.SmallIntegerField(blank=True, null=True,default=0)
    status = models.SmallIntegerField(blank=True, null=True, default=0)
    mark = models.TextField(blank=True, null=True)
    receive_name = models.CharField(max_length=100, null=True)
    province = models.CharField(max_length=100, null=True)
    shi = models.CharField(max_length=100, null=True)
    qu = models.CharField(max_length=100, null=True)

    uid = models.ForeignKey('User', models.CASCADE, db_column='uid', blank=True, null=True)


    class Meta:
        # managed = False
        db_table = 'order'



class Cart(models.Model): #购物车
    ccid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100,blank=True,null=True)
    create_time = models.DateTimeField(blank=True, null=True)
    paytime = models.DateTimeField(blank=True, null=True)
    unit_price = models.IntegerField(blank=True, null=True)
    total_price = models.IntegerField(blank=True, null=True)
    num = models.IntegerField(blank=True, null=True)
    isdel = models.SmallIntegerField(blank=True, null=True,default=0)
    iscollect = models.SmallIntegerField(blank=True, null=True,default=0)
    arrt = models.CharField(max_length=200,blank=True,null=True)
    pid = models.ForeignKey('Products', models.CASCADE, db_column='pid', blank=True, null=True)
    uid = models.ForeignKey('User', models.CASCADE, db_column='uid', blank=True, null=True)
    class Meta:
        # managed = False
        db_table = 'cart'




class Products(models.Model):
    pid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=600)
    content = models.TextField(blank=True, null=True)
    size = models.CharField(max_length=100,blank=True,null=True)
    pscore = models.IntegerField(default=100,null=True,blank=True)
    status = models.IntegerField(blank=True, null=True)
    hits = models.IntegerField(blank=True, null=True)
    num = models.IntegerField(blank=True, null=True)
    istop = models.IntegerField(blank=True, null=True)
    iscart = models.IntegerField(blank=True, null=True,default=0)#加入购物车
    ishot = models.IntegerField(blank=True, null=True,default=0)
    price = models.IntegerField(blank=True, null=True)
    isdel = models.SmallIntegerField(blank=True, null=True,default=0)
    publishtime = models.DateTimeField(blank=True, null=True)
    cid = models.ForeignKey(Category, models.CASCADE, db_column='cid', blank=True, null=True)
    ccid = models.ForeignKey(Cart, models.CASCADE, db_column='ccid', blank=True, null=True)#购物车
    # uid = models.ForeignKey('User', models.CASCADE, db_column='uid', blank=True, null=True)
    oid = models.ForeignKey(Order, models.CASCADE, db_column='oid', blank=True, null=True)
    coid = models.ForeignKey('Collections', models.CASCADE, db_column='coid', blank=True, null=True)#收藏夹


    class Meta:
        # managed = False
        db_table = 'products'


class Addressdetail(models.Model):
    rid = models.AutoField(primary_key=True)
    receivename = models.CharField(max_length=100,blank=True, null=True)
    content = models.CharField(max_length=1000, blank=True, null=True)
    isdefault = models.IntegerField(blank=True, null=True, default=0)
    phone = models.CharField(max_length=20, blank=True, null=True, default=0)
    receivetime = models.DateTimeField(blank=True, null=True)
    isdel = models.SmallIntegerField(blank=True, null=True,default=0)
    iscontribute = models.SmallIntegerField(blank=True, null=True,default=0)#是否配送
    oid = models.ForeignKey(Order, models.CASCADE, db_column='oid', blank=True, null=True)#一对一
    uid = models.ForeignKey('User', models.CASCADE, db_column='uid', blank=True, null=True)

    class Meta:
        
        db_table = 'addressdetail'


class Siteinfo(models.Model):
    sitename = models.CharField(max_length=100, blank=True, null=True)
    website = models.CharField(max_length=100, blank=True, null=True)
    url = models.CharField(max_length=200, blank=True, null=True)
    reference = models.CharField(max_length=200, blank=True, null=True)
    isclose = models.IntegerField(blank=True, null=True)

    class Meta:
        # managed = False
        db_table = 'siteinfo'


class User(AbstractUser):
    # password = models.CharField(max_length=128)
    phonenumber = models.CharField(max_length=128,blank=True, null=True)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    # username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    is_staff = models.IntegerField(blank=True, null=True)
    is_active = models.IntegerField(blank=True, null=True)
    date_joined = models.DateTimeField(blank=True, null=True)
    uid = models.AutoField(primary_key=True)
    portrait = models.CharField(max_length=100, blank=True, null=True)
    gender = models.IntegerField(blank=True, null=True)
    usertype = models.IntegerField(blank=True, null=True)
    email = models.CharField(max_length=200, blank=True, null=True)
    autologin = models.IntegerField(blank=True, null=True)
    regtime = models.DateTimeField(blank=True, null=True)
    score = models.IntegerField(blank=True, null=True,default=100)

    class Meta:
        # managed = False
        db_table = 'user'


class Userdetail(models.Model):
    birthday = models.DateField(blank=True, null=True)
    address = models.CharField(max_length=200, blank=True, null=True)
    qq = models.CharField(max_length=15, blank=True, null=True)
    signature = models.CharField(max_length=200, blank=True, null=True)
    quesstion = models.CharField(max_length=100, blank=True, null=True)
    answer = models.CharField(max_length=200, blank=True, null=True)
    grade = models.CharField(max_length=100, blank=True, null=True)
    uid = models.ForeignKey(User, models.CASCADE, db_column='uid',blank=True, null=True)


    class Meta:
        # managed = False
        db_table = 'userdetail'


class Collections(models.Model):
    coid = models.AutoField(primary_key=True)
    name = models.CharField(blank=True, null=True,max_length=30)
    price = models.IntegerField(blank=True, null=True)
    isdel = models.SmallIntegerField(blank=True, null=True,default=0)
    iscart = models.SmallIntegerField(blank=True, null=True,default=0)
    create_time = models.DateTimeField(blank=True, null=True)



    class Meta:
        # managed = False
        db_table = 'collections'

cake2/templates/app/integral.html
{% extends 'app/base.html' %}

{% block css %}
    <link href="http://www.holiland.com/statics/css/global.css" rel="stylesheet" type="text/css">
<link href="http://www.holiland.com/statics/css/member.css" rel="stylesheet" rev="stylesheet" type="text/css" media="all">
<script language="JavaScript" src="http://www.holiland.com/statics/js/jquery.min.js"></script>
<script src="http://www.holiland.com/statics/js/layer/layer.js" ></script>
<script src="http://www.holiland.com/statics/js/ajaxForm.js" ></script>
<script src="http://www.holiland.com/statics/js/common.js" ></script>
<style type="text/css">
.paysubmit{float:left; margin-left:10px;cursor: pointer; border:none; display: block;height: 40px;line-height: 40px;text-align: center;width: 100px;background: none repeat scroll 0% 0% #87D0E3;font-size: 16px; color:#fff;}
#syl_but{
  float: left;
  margin-left: 10px;
  cursor: pointer;
  border: none;
  display: block;
  height: 40px;
  line-height: 40px;
  text-align: center;
  width: 100px;
  background: none repeat scroll 0% 0% #87D0E3;
  font-size: 16px;
  color: #fff;
}
</style>
</head>

{% endblock css %}

{% block body %}
    <div class="hll_meb">

		<div class="hll_meb_l">
	<div class="help_menu">
		<div class="tit"><span></span><h3>业务功能</h3></div>
		<ul>
			<li><a href="{% url 'app:order' %} ">查看订单</a></li>
			<li><a href="{% url 'app:favorite' %} ">收藏夹</a></li>
{#			<li><a href="{% url 'app:friend' %} ">我的亲友</a></li>#}
			<li><a href="{% url 'app:address' %} ">收货地址簿</a></li>
{#			<li><a href="{% url 'app:integral' %} ">我的积分</a></li>#}
{#			<li><a href="{% url 'app:bonus' %} ">我的优惠券</a></li>#}
			<!-- <li><a href="user.php?act=exchange">兑换优惠券</a></li> -->
			<!-- <li><a href="user.php?act=return">退换货申请</a></li> -->
{#			<li><a href="{% url 'app:message' %} ">投诉和建议</a></li>#}
		</ul>
	</div>
	<div class="help_menu">
		<div class="tit"><span></span><h3>个人信息</h3></div>
		<ul>
			<li><a href="{% url 'app:changem' %} ">更换手机号</a></li>
			<li><a href="{% url 'app:editpwd' %} ">修改密码</a></li>
			<li><a href="{% url 'app:editpwd' %} ">编辑用户信息</a></li>
		</ul>
	</div>
	<div class="help_menu">
		<div class="tit"><span></span><h3>其他功能</h3></div>
		<ul>
			<li><a href="{% url 'app:index' %}" class="opAjax" data-confirm="0" data-ismsg="1">退出</a></li>
			<li><a href="{% url 'app:user' %}">返回帐户首页</a></li>
		</ul>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	var objStr = ".help_menu div.tit span";
	$(objStr).each(function(i){
		$(this).click(function(){
			$($(".help_menu div.tit")[i]).next("ul").slideToggle(20);
			$(this).toggleClass("cur");
			$(this).siblings("span").removeClass("cur");
		});
	});

	$(".help_menu ul li").mouseover(function () {
		$(this).addClass('Bg_hover');
	});
	$(".help_menu ul li").mouseout(function () {
		$(this).removeClass('Bg_hover');
	});
});
</script>

	<div class="hll_meb_r">

				<div class="hll_memDD">
			<div class="tit">
				<h3 class="meb_bt">我的积分</h3>
				<div class="hll_intro">
					<label>您在本商城的总积分为 <span>100积分</span> ，可用积分 <span>100积分</span> </label>
				</div>
			</div>
		</div>

		<div class="hll_memDD hll_memList">
			<table border="0" cellpadding="0" cellspacing="0">
				<tbody>
					<tr>
						<th class="text_10" width="16%">积分类型</th>
						<th width="16%"><span>积分数（分）</span></th>
						<th width="20%"><span>时间</span></th>
						<th><span>备注</span></th>
					</tr>
										<tr>
						<td><font color="red">获取积分</font></td>
						<td>100</td>
						<td>2019-09-11</td>
						<td>&nbsp;&nbsp;</td>
					</tr>
									</tbody>
			</table>
		</div>

		<div class="use_table_f">
			<div class="cz_left"><b>积分总数：100积分</b></div>
			<div class="hll_page hll_mebPage">
			<img src="http://www.holiland.com/statics/images/up.jpg">
			<a href="http://www.holiland.com//user.php?act=integral&page=1" class="xz">1</a>
			<img src="http://www.holiland.com/statics/images/down.jpg">
		</div>		</div>





		<!--#兑换优惠券页面 start>-->







	</div>
</div>



{% endblock %}

cake2/templates/app/profile.html
{% extends 'app/base.html' %}
{% load static %}
{% block css %}
    <link href="http://www.holiland.com/statics/css/global.css" rel="stylesheet" type="text/css">
<link href="http://www.holiland.com/statics/css/member.css" rel="stylesheet" rev="stylesheet" type="text/css" media="all">

<style type="text/css">
.paysubmit{float:left; margin-left:10px;cursor: pointer; border:none; display: block;height: 40px;line-height: 40px;text-align: center;width: 100px;background: none repeat scroll 0% 0% #87D0E3;font-size: 16px; color:#fff;}
#syl_but{
  float: left;
  margin-left: 10px;
  cursor: pointer;
  border: none;
  display: block;
  height: 40px;
  line-height: 40px;
  text-align: center;
  width: 100px;
  background: none repeat scroll 0% 0% #87D0E3;
  font-size: 16px;
  color: #fff;
}
</style>

{% endblock %}

{% block script %}
    <script language="JavaScript" src="/static/js/jquery.min.js"></script>
    <script src="/static/js/layer/layer.js" ></script>
    <script src="/static/js/ajaxForm.js" ></script>
    <script src="/static/js/common.js" ></script>


{% endblock %}




{% block body %}
    <div class="hll_meb">

		<div class="hll_meb_l">
	<div class="help_menu">
		<div class="tit"><span></span><h3>业务功能</h3></div>
		<ul>
			<li><a href="{% url 'app:order' %} ">查看订单</a></li>
			<li><a href="{% url 'app:favorite' %} ">收藏夹</a></li>
{#			<li><a href="{% url 'app:friend' %} ">我的亲友</a></li>#}
			<li><a href="{% url 'app:address' %} ">收货地址簿</a></li>
{#			<li><a href="{% url 'app:integral' %} ">我的积分</a></li>#}
{#			<li><a href="{% url 'app:bonus' %} ">我的优惠券</a></li>#}
			<!-- <li><a href="user.php?act=exchange">兑换优惠券</a></li> -->
			<!-- <li><a href="user.php?act=return">退换货申请</a></li> -->
{#			<li><a href="{% url 'app:message' %} ">投诉和建议</a></li>#}
		</ul>
	</div>
	<div class="help_menu">
		<div class="tit"><span></span><h3>个人信息</h3></div>
		<ul>
			<li><a href="{% url 'app:changem' %} ">更换手机号</a></li>
			<li><a href="{% url 'app:editpwd' %} ">修改密码</a></li>
			<li><a href="{% url 'app:profile' %} ">编辑用户信息</a></li>
		</ul>
	</div>
	<div class="help_menu">
		<div class="tit"><span></span><h3>其他功能</h3></div>
		<ul>
			<li><a href="{% url 'app:index' %}" class="opAjax" data-confirm="0" data-ismsg="1">退出</a></li>
			<li><a href="{% url 'app:user' %}">返回帐户首页</a></li>
		</ul>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	var objStr = ".help_menu div.tit span";
	$(objStr).each(function(i){
		$(this).click(function(){
			$($(".help_menu div.tit")[i]).next("ul").slideToggle(20);
			$(this).toggleClass("cur");
			$(this).siblings("span").removeClass("cur");
		});
	});

	$(".help_menu ul li").mouseover(function () {
		$(this).addClass('Bg_hover');
	});
	$(".help_menu ul li").mouseout(function () {
		$(this).removeClass('Bg_hover');
	});
});
</script>

	<div class="hll_meb_r">

		<!--#兑换优惠券页面 start>-->

        <script language=javascript src="/static/js/region_flow.js"></script>
		<script language=javascript src="/static/js/My97DatePicker/WdatePicker.js"></script>
		<div class="hll_memDD">
			<div class="tit">
				<h3 class="meb_bt">编辑用户信息</h3>
			</div>
		</div>
		<form name="fguserForm" method="post" action="{% url 'app:profile' %}" class="ajaxForm">
            {% csrf_token %}
			<input name="act" type="hidden" value="act_edit_profile" />
			<div class="meb_bjxx">
				<ul>
					<li class="text_right" style="text-align:right;">您的用户名：</li>
					<li>{{ user.username }}</li>
				</ul>
				<ul>
					<li class="text_right" style="text-align:right;">电子邮箱：</li>
					<li>{{ user.email }}
{#						<div class="xx"><input name="email" value="{{ user.email }}" class="bg" type="text"></div>#}
					</li>
				</ul>
                <ul>
					<li class="text_right" style="text-align:right;">手机号：</li>
					<li>{{ user.phonenumber }}
{#						<div class="xx"><input name="email" value="{{ user.email }}" class="bg" type="text"></div>#}
					</li>
				</ul>
				<ul class="hg">
					<li class="text_right" style="text-align:right;">昵称：</li>
					<li>
						<div class="xx"><input name="nickname" value="{{ user.userdetail_set.get.signature }}" class="bg" type="text"></div>
						<span class="ts">
							昵称可以由英文字母、中文、数字组成。
						</span>
					</li>
				</ul>
				<!--<ul class="hg">
					<li class="text_right">真实姓名：</li>
					<li>
						<div class="xx"><input name="realname" value="13148636172" class="bg" type="text"></div>
						<span class="ts">
							请输入您的真实姓名。
						</span>
					</li>
				</ul>-->
				<ul>
					<li class="text_right" style="text-align:right;">性别：</li>
					<li>
						<div class="xx">
{#							<input name="sex" value="1" type="radio">先生<input name="sex" value="0" checked="checked" type="radio">女士#}
						    <select name="sex" id="sex" class="ps">
						        <option value="0" {% ifequal user.gender 0 %}selected="selected" {% endifequal %}>保密</option>
						        <option value="1" {% ifequal user.gender 1 %}selected="selected" {% endifequal %}>女</option>
						        <option value="2" {% ifequal user.gender 2 %}selected="selected" {% endifequal %}>男</option>
					        </select>
                        </div>
					</li>
				</ul>
{#				<ul>#}
{#					<li class="text_right" style="text-align:right;">生日历法：</li>#}
{#					<li>#}
{#						<div class="xx">#}
{#							<select name="birthdaytype">#}
{#								<option value="" selected="selected">请选择</option>#}
{#								<option value="yangli">阳历</option>#}
{#								<option value="yinli">阴历</option>#}
{#							</select>#}
{#						</div>#}
{#					</li>#}
{#				</ul>#}
				<ul>
					<li class="text_right" style="text-align:right;">生日：</li>
					<li>
						<div class="xx">

							<input name="birthday" value="{{ user.userdetail_set.get.birthday | date:"Y-m-d"}}" lass="bg" type="date" ><font style="color:#c0c0c0"></font>
{#                            <input name="birthday" value="{{ user.userdetail_set.get.birthday }}" onclick="" class="bg" type="text" ><font style="color:#c0c0c0"></font>#}
                                {#{{ user.userdetail_set.get.birthday|date:"Y-m-d" }}#}
                        </div>
					</li>
				</ul>
				<!--
				//邮政号码
				<ul class="hg">
					<li class="text_right">邮政编码：</li>
					<li>
						<div class="xx"><input name="zipcode" maxlength="6" value="" style="ime-mode:disabled" class="bg" type="text"></div>
						<span class="ts">
							请输入6位邮政编码。
						</span>
					</li>
				</ul>
				//身份证号
				<ul class="hg">
					<li class="text_right">身份证号：</li>
					<li>
						<div class="xx"><input name="idcard" maxlength="18" value="" class="bg" type="text"></div>
						<span class="ts">
							请输入18位身份证号。
						</span>
					</li>
				</ul>-->
								<script type="text/javascript">
				//所在区域
				/*<ul>
					<li class="text_right">所在地区：</li>
					<li>
						<div id="systemareadiv0" class="xx">
							<table cellpadding="0" cellspacing="1">
								<tbody>
									<tr>
										<td id="provincialId">
											<select name="country" id="selCountries" onchange="region.changed(this, 1, 'selProvinces')" class="input100">
												<option value="0">请选择</option>
																								<option value="1" >中国</option>
																							</select>
											<select name="province" id="selProvinces" onchange="region.changed(this, 2, 'selCities')" class="input100">
												<option value="0">请选择</option>
																								<option value="2" >北京</option>
																								<option value="4359" >广东</option>
																								<option value="4108" >山西</option>
																								<option value="5904" >杭州</option>
																								<option value="4120" >山东</option>
																								<option value="4121" >河南</option>
																								<option value="4122" >江苏</option>
																								<option value="4123" >浙江</option>
																								<option value="4124" >安徽</option>
																								<option value="4125" >江西</option>
																								<option value="4381" >贵州</option>
																								<option value="4126" >福建</option>
																								<option value="4127" >湖北</option>
																								<option value="4128" >重庆</option>
																								<option value="4129" >上海</option>
																								<option value="4388" >云南</option>
																								<option value="4408" >甘肃</option>
																								<option value="4422" >宁夏</option>
																								<option value="4428" >广西</option>
																								<option value="3419" >四川</option>
																								<option value="4443" >内蒙古</option>
																								<option value="3425" >河北</option>
																								<option value="3428" >天津</option>
																								<option value="3431" >辽宁</option>
																								<option value="3432" >吉林</option>
																								<option value="3433" >黑龙江</option>
																								<option value="3437" >陕西</option>
																								<option value="4345" >湖南</option>
																								<option value="6649" >西藏</option>
																							</select>
											<select name="city" id="selCities" onchange="region.changed(this, 3, 'selDistricts')" class="input100">
												<option value="0">请选择</option>
																							</select>
											<select name="district" id="selDistricts" style="display:none" class="input100">
												<option value="0">请选择</option>
																							</select>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</li>
				</ul>
				//地址
				<ul class="hg">
					<li class="text_right">地址：</li>
					<li>
						<div class="xx"><input name="address" value="" class="bg" type="text"></div>
						<span class="ts">
							请输入详细地址。
						</span>
					</li>
				</ul>*/
				</script>
				<ul>
					<li class="text_right"></li>
					<li>
{#						<a href="javascript:;" data-ismsg="1" class="tj submitbtn">提交</a>#}
                        <button type="submit" name="profilesubmitbtn" id="profilesubmitbtn" value="true" class="pn pnc" onclick="alert('修改成功')" style="width: 120px;height: 40px;background-color: #87D0E3;font-size: 18px;">
                            <p style="color: white">保&nbsp;&nbsp;&nbsp;存</p>
                        </button>
					</li>
				</ul>
			</div>
			<script>
			$(document).ready(function(){
				$(".meb_bjxx ul.hg").mouseover(function () {
					$(this).find("span.ts").show();
					//$(this).addClass('hover_bg');
				})
				$(".meb_bjxx ul.hg").mouseout(function () {
					$(this).find("span.ts").hide();
					//$(this).removeClass('hover_bg');
				});
			});

			</script>
		</form>

	</div>
</div>


{% endblock %}

cake2/templates/app/we.html
{% extends 'app/base.html' %}
{% load static %}


{% block title %}
    <title>关于我们</title>
{% endblock %}

{% block body %}

    <div class="hll_zxDetail" style="width:996px;margin-left: 15%">
		<div class="login_bt" style="text-align:center; padding-left:0; width:996px; background:#fff; line-height:30px; height:30px; margin-bottom:10px;">
			<span style="float:left; width:40%; display:inline-block; border-top:1px dashed #d5d5d5; margin-top:14px;"></span>
			<span style="width:15%; display:inline-block; color:#909090; font-weight:bold; font-size:16px;">关于我们</span>
			<span style="float:right; width:40%; display:inline-block; border-top:1px dashed #d5d5d5; margin-top:14px;"></span>
		</div>
		<!-- <h2 style="border-bottom:1px dashed #cececb; padding-bottom:15px; margin-bottom:15px;">关于我们</h2> -->
		<!-- <div class="nr_xx"></div>
		<div class="nr_ms" style="width:100%;">
			<p class="p1" style="text-align: center;">
				<span style="color: rgb(0, 204, 255);">
				<span style="font-size: 24px;">
					<span style="font-family: 黑体;">
						<strong><u>关于我们<br><br></u></strong>
					</span>
				</span>
				</span>
			</p>
		</div> -->
		<div>
		<p><img src="/static/imgaes/imgs/1544409927136109.jpg" alt="关于我们1.jpg"></p>		</div>
	</div>

{% endblock %}